@startuml user_requests_erd_example
'Версия: 1.0
'Автор: Окунев Е.Е. (okunev.evgeni@gmail.com)

!function $pk($a)
!return "<color:RoyalBlue>" + $a + " <<PK>></color>"
!endfunction

!function $unique($a)
!return "<color:Crimson>" + $a + " <<unique>></color>"
!endfunction

!function $setBold($a)
!return "<b>" + $a + " </b>"
!endfunction

skinparam BackgroundColor SeaShell
skinparam LegendBackgroundColor MistyRose
skinparam LegendBorderColor PaleVioletRed
skinparam LegendFontColor PaleVioletRed

skinparam Class {
    HeaderBackgroundColor PaleGreen
}

'skinparam linetype ortho
skinparam TitleFontColor Sienna

Header Пример ER-диаграммы
Title ER-диаграмма "Заявка пользователя"

entity "$setBold("Пользователь (users)")" as users {
    * $pk("id")
    ..
    * $unique("username")
    * password
    * name
    * surname
    patronimyc
    * email
    is_active <<default true>>
    birth_date
    created_at
    updated_at
}

entity "$setBold("Заявка (requests)")" as requests {
    * $pk("id")
    ..
    * description
    created_at
    updated_at
}

entity "$setBold("Сервис (services)")" as services {
    * $pk("id")
    ..
    * name
    * is_enable <<default true>>
    default_route
}

entity "$setBold("Вложение (files)")" as files {
    * $pk("id")
    ..
    * size
    * name
    * url
    mime_type
    created_at
    updated_at
}

entity "$setBold("Статус (statuses)")" as statuses {
    * $pk("id")
    ..
    * name
}

users ||-o{ requests : создает
users ||-o{ requests : изменяет
users ||-----o{ requests

requests }o-down-|| services : принадлежит
requests }o-up-|| statuses
requests ||-right-o| files


legend right
$setBold("Условные обозначения:")
* - обязательное поле
PK - первичный ключ
end legend

footer Evgeni Okunev, 2023

@enduml