@startuml

!function $pk($a)
!return "<color:RoyalBlue>" + $a + " <<PK>></color>"
!endfunction

!function $setBold($a)
!return "<b>" + $a + " </b>"
!endfunction

skinparam ClassHeaderBackgroundColor PaleGreen

entity "$setBold("Издательство")" as Publisher {
    * $pk("Название")
    Адрес
}

entity "$setBold("Издание")" as Edition {
    * $pk("ISBN")
    * Название
    Автор
    Год_издания
    Количество_страниц
}

entity "$setBold("Категория")" as Category {
    * $pk("Название")
}

entity "$setBold("Экземпляр")" as Copy {
    * $pk("Номер_копии")
    Место_на_полке
}

entity "$setBold("Читатель")" as Reader {
    * $pk("Идентификатор")
    Имя
    Фамилия
    Адрес
    Дата_рождения
}

entity "$setBold("Выдача")" as Loan {
    * $pk("ID_выдачи")
    Дата_выдачи
    Плановая_дата_возврата
    Фактическая_дата_возврата
}

Publisher ||--o{ Edition : "Выпускает"
Edition }o--|{ Category : "Относится к"
Category }o--|| Category : "Является подкатегорией"
Edition ||--o{ Copy : "Имеет экземпляры"
Reader ||--o{ Loan : "Берёт книги"
Copy ||--o{ Loan : "Выдается читателю"

@enduml
