/'
**Спортивные матчи**:
- В системе хранится информация о матчах между командами.
- Каждый матч проходит между двумя командами под руководством одного арбитра.
- Команды могут играть друг с другом или другими командами не ограниченное количество раз.
- Арбитр может судить разные матчи.
'/