/'
Задание:
В библиотеке хранятся книги (издания). Каждая книга (издание) имеет уникальный идентификатор, название, автора, год
издания и количество страниц. Книги издаются издательствами, у которых есть название и адрес. В библиотеке есть
экземпляры книг (физические/электронные копии издания). Каждый экземпляр имеет уникальный идентификатор и положение на
полке. Экземпляр книги связан с конкретной книгой. Книги могут принадлежать одной или нескольким категориям. Категории
могут быть вложенными (одна категория может быть подкатегорией другой). У каждой категории есть название. В библиотеке
есть читатели. Каждый читатель имеет уникальный идентификатор, имя, фамилию, адрес и дату рождения. Читатель может брать
книги на определенный срок. Для каждой выдачи книги записывается дата, когда книга была взята, планируемая дата возврата
и фактическая дата возврата (если книга уже возвращена).
'/