@startuml
entity "Страна" as Country
entity "Город" as City
entity "Улица" as Street
entity "Дом" as Building
entity "Квартира" as Apartment

Country ||--o{ City : "Содержит"
City ||--o{ Street : "Содержит"
Street ||--o{ Building : "Содержит"
Building ||--o{ Apartment : "Содержит"
@enduml
