@startuml
entity "Мужчина" as Man
entity "Женщина" as Woman

' Роль отца (Мужчина является отцом для мужчин и женщин)
Man |o--o{ Man : "Отец"
Man |o--o{ Woman : "Отец"

' Роль матери (Женщина является матерью для мужчин и женщин)
Woman |o--o{ Man : "Мать"
Woman |o--o{ Woman : "Мать"
@enduml
