/'
**Спортивные матчи**:
- В системе хранится информация о матчах между командами.
- Каждый матч проходит между двумя командами под руководством одного арбитра.
- Команда может играть с одной командой или другими командами не ограниченное количество раз.
- Арбитр может судить разные матчи.
'/